AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Glue Table for analytics_raw_schema with Parquet format and partitioning'

Parameters:
  DatabaseName:
    Type: String
    Default: metrics-pc
    Description: Name of the Glue database

  TableName:
    Type: String
    Default: analytics_raw_schema
    Description: Name of the Glue table

  S3BucketName:
    Type: String
    Default: pc-analytics-321321
    Description: S3 bucket name where data is stored

  S3Prefix:
    Type: String
    Default: analytics/
    Description: S3 prefix for the table data

Resources:
  AnalyticsTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref DatabaseName
      TableInput:
        Name: !Ref TableName
        Description: 'Analytics raw data table with Parquet format, partitioned by year, month, day, hour'
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: 'parquet'
          typeOfData: 'file'
          EXTERNAL: 'TRUE'
          'parquet.compress': 'SNAPPY'
        StorageDescriptor:
          Columns:
            - Name: ts
              Type: double
              Comment: 'Unix timestamp'
            - Name: timestamp
              Type: string
              Comment: 'Formatted timestamp string'
            - Name: epoch_timestamp
              Type: double
              Comment: 'Epoch timestamp from ts field'
            - Name: date
              Type: string
              Comment: 'Date string (YYYY-MM-DD)'
            - Name: minute
              Type: string
              Comment: 'Minute (00-59)'
            - Name: datetime
              Type: string
              Comment: 'Datetime string'
            - Name: _processed_at
              Type: string
              Comment: 'ISO timestamp when record was processed'
            - Name: _processed_timestamp
              Type: bigint
              Comment: 'Unix timestamp when record was processed'
            - Name: interval_s
              Type: int
              Comment: 'Collection interval in seconds'
            - Name: cpu_pct
              Type: double
              Comment: 'CPU usage percentage'
            - Name: ram_pct
              Type: double
              Comment: 'RAM usage percentage'
            - Name: hostname
              Type: string
              Comment: 'Hostname of the system'
            - Name: os
              Type: string
              Comment: 'Operating system name'
            - Name: os_v
              Type: string
              Comment: 'Operating system version'
            - Name: arch
              Type: string
              Comment: 'System architecture'
            - Name: node_role
              Type: string
              Comment: 'Node role identifier'
            - Name: env
              Type: string
              Comment: 'Environment identifier'
            - Name: session_id
              Type: string
              Comment: 'Session identifier'
            - Name: day_of_week
              Type: string
              Comment: 'Day of week name'
            - Name: net_bytes_sent_per_s
              Type: double
              Comment: 'Network bytes sent per second'
            - Name: net_bytes_recv_per_s
              Type: double
              Comment: 'Network bytes received per second'
            - Name: net_packets_sent_per_s
              Type: double
              Comment: 'Network packets sent per second'
            - Name: net_packets_recv_per_s
              Type: double
              Comment: 'Network packets received per second'
            - Name: net_err_in_per_s
              Type: double
              Comment: 'Network input errors per second'
            - Name: net_err_out_per_s
              Type: double
              Comment: 'Network output errors per second'
            - Name: net_drop_in_per_s
              Type: double
              Comment: 'Network input drops per second'
            - Name: net_drop_out_per_s
              Type: double
              Comment: 'Network output drops per second'
            - Name: disk_read_bytes_per_s
              Type: double
              Comment: 'Disk read bytes per second'
            - Name: disk_write_bytes_per_s
              Type: double
              Comment: 'Disk write bytes per second'
            - Name: disk_read_ops_per_s
              Type: double
              Comment: 'Disk read operations per second'
            - Name: disk_write_ops_per_s
              Type: double
              Comment: 'Disk write operations per second'
          Location: !Sub 's3://${S3BucketName}/${S3Prefix}'
          InputFormat: 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
          OutputFormat: 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
          SerdeInfo:
            SerializationLibrary: 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
            Parameters:
              serialization.format: '1'
              'parquet.compress': 'SNAPPY'
          Compressed: true
        PartitionKeys:
          - Name: year
            Type: string
            Comment: 'Partition by year'
          - Name: month
            Type: string
            Comment: 'Partition by month (01-12)'
          - Name: day
            Type: string
            Comment: 'Partition by day (01-31)'
          - Name: hour
            Type: string
            Comment: 'Partition by hour (00-23)'

Outputs:
  TableName:
    Description: 'Name of the created Glue table'
    Value: !Ref AnalyticsTable
    Export:
      Name: !Sub '${AWS::StackName}-TableName'

  TableArn:
    Description: 'ARN of the created Glue table'
    Value: !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/${DatabaseName}/${AnalyticsTable}'
    Export:
      Name: !Sub '${AWS::StackName}-TableArn'
